api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate MRI version for an app"
  homepage = "https://github.com/paketo-buildpacks/mri"
  id = "paketo-buildpacks/mri"
  keywords = ["ruby", "mri"]
  name = "Paketo Buildpack for MRI"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/mri/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    ruby = "3.1.*"

  [[metadata.dependencies]]
    checksum = "sha256:87da799d2a3b203296790035b0b77d5d07f9d4cccb0979e7395663e187c03f5e"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.5:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.5?checksum=3685c51eeee1352c31ea039706d71976f53d00ab6d77312de6aa1abaf5cda2c5&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.5.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.5.tar.gz"
    source-checksum = "sha256:3685c51eeee1352c31ea039706d71976f53d00ab6d77312de6aa1abaf5cda2c5"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.5_linux_x64_jammy_87da799d.tgz"
    version = "3.1.5"

  [[metadata.dependencies]]
    checksum = "sha256:9ed8b96eb4df430bffa807542a4e12f890c5e92fe507d96e194e4e528f97f618"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.5:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.5?checksum=3685c51eeee1352c31ea039706d71976f53d00ab6d77312de6aa1abaf5cda2c5&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.5.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.5.tar.gz"
    source-checksum = "sha256:3685c51eeee1352c31ea039706d71976f53d00ab6d77312de6aa1abaf5cda2c5"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.5_linux_x64_bionic_9ed8b96e.tgz"
    version = "3.1.5"

  [[metadata.dependencies]]
    checksum = "sha256:2b41783bf4e4ccaed44498c05615f61455d556380b4fca641eba135832a2b063"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.6:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.6?checksum=0d0dafb859e76763432571a3109d1537d976266be3083445651dc68deed25c22&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.6.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.6.tar.gz"
    source-checksum = "sha256:0d0dafb859e76763432571a3109d1537d976266be3083445651dc68deed25c22"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.6_linux_x64_jammy_2b41783b.tgz"
    version = "3.1.6"

  [[metadata.dependencies]]
    checksum = "sha256:6d1e6b48e5de98f5fdcad5c06efc9a8f30c28bfe8e310918781f10ed531a4fe2"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.6:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.6?checksum=0d0dafb859e76763432571a3109d1537d976266be3083445651dc68deed25c22&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.6.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.6.tar.gz"
    source-checksum = "sha256:0d0dafb859e76763432571a3109d1537d976266be3083445651dc68deed25c22"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.6_linux_x64_bionic_6d1e6b48.tgz"
    version = "3.1.6"

  [[metadata.dependencies]]
    checksum = "sha256:7e7ac3e87d9daa8ccafeb2de956ea5f04e19ac014dcfcce0c4e316c5e835f995"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.4?checksum=c72b3c5c30482dca18b0f868c9075f3f47d8168eaf626d4e682ce5b59c858692&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.4.tar.gz"
    source-checksum = "sha256:c72b3c5c30482dca18b0f868c9075f3f47d8168eaf626d4e682ce5b59c858692"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.4_linux_x64_jammy_7e7ac3e8.tgz"
    version = "3.2.4"

  [[metadata.dependencies]]
    checksum = "sha256:89cb55b942d98fe7e216cd45aea409c6e3a3d0d22e0c681258dc41f8fc5d2803"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.4?checksum=c72b3c5c30482dca18b0f868c9075f3f47d8168eaf626d4e682ce5b59c858692&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.4.tar.gz"
    source-checksum = "sha256:c72b3c5c30482dca18b0f868c9075f3f47d8168eaf626d4e682ce5b59c858692"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.4_linux_x64_bionic_89cb55b9.tgz"
    version = "3.2.4"

  [[metadata.dependencies]]
    checksum = "sha256:4594dc4ea25ca7c4dc05a189c1497a7db83e339db8f11658e2735008cd609a12"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.5:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.5?checksum=ef0610b498f60fb5cfd77b51adb3c10f4ca8ed9a17cb87c61e5bea314ac34a16&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.5.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.5.tar.gz"
    source-checksum = "sha256:ef0610b498f60fb5cfd77b51adb3c10f4ca8ed9a17cb87c61e5bea314ac34a16"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.5_linux_x64_jammy_4594dc4e.tgz"
    version = "3.2.5"

  [[metadata.dependencies]]
    checksum = "sha256:a23f21e0b06d0b32ff31cb75e9eea1dd4d0e26f1ea2e7577324fe3c548441bce"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.5:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.5?checksum=ef0610b498f60fb5cfd77b51adb3c10f4ca8ed9a17cb87c61e5bea314ac34a16&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.5.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.5.tar.gz"
    source-checksum = "sha256:ef0610b498f60fb5cfd77b51adb3c10f4ca8ed9a17cb87c61e5bea314ac34a16"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.5_linux_x64_bionic_a23f21e0.tgz"
    version = "3.2.5"

  [[metadata.dependencies]]
    checksum = "sha256:6398ad2554681490cd024826f397bd766bf958e05f2f665285db906134cae6fb"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.3.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.3.4?checksum=fe6a30f97d54e029768f2ddf4923699c416cdbc3a6e96db3e2d5716c7db96a34&download_url=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.4.tar.gz"
    source-checksum = "sha256:fe6a30f97d54e029768f2ddf4923699c416cdbc3a6e96db3e2d5716c7db96a34"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.3.4_linux_x64_jammy_6398ad25.tgz"
    version = "3.3.4"

  [[metadata.dependencies]]
    checksum = "sha256:19180e31c3d53add65fe1b973199f088f617cefa5cb2d5702a2737fd56bde5e5"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.3.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.3.4?checksum=fe6a30f97d54e029768f2ddf4923699c416cdbc3a6e96db3e2d5716c7db96a34&download_url=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.4.tar.gz"
    source-checksum = "sha256:fe6a30f97d54e029768f2ddf4923699c416cdbc3a6e96db3e2d5716c7db96a34"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.3.4_linux_x64_bionic_19180e31.tgz"
    version = "3.3.4"

  [[metadata.dependencies]]
    checksum = "sha256:3e9613092b8d7d39067b5e6eb9816af1b3d63ffdda3ccf1891cd2d7849e4aa31"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.3.5:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.3.5?checksum=3781a3504222c2f26cb4b9eb9c1a12dbf4944d366ce24a9ff8cf99ecbce75196&download_url=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.5.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.5.tar.gz"
    source-checksum = "sha256:3781a3504222c2f26cb4b9eb9c1a12dbf4944d366ce24a9ff8cf99ecbce75196"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.3.5_linux_x64_jammy_3e961309.tgz"
    version = "3.3.5"

  [[metadata.dependencies]]
    checksum = "sha256:c8c615437c523e71c75c8a871fa2c46f9e5fd990a6d0f12aa39b05234406021f"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.3.5:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.3.5?checksum=3781a3504222c2f26cb4b9eb9c1a12dbf4944d366ce24a9ff8cf99ecbce75196&download_url=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.5.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.5.tar.gz"
    source-checksum = "sha256:3781a3504222c2f26cb4b9eb9c1a12dbf4944d366ce24a9ff8cf99ecbce75196"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.3.5_linux_x64_bionic_c8c61543.tgz"
    version = "3.3.5"

  [[metadata.dependencies]]
    checksum = "sha256:55a4cd1dcbe5ca27cf65e89a935a482c2bb2284832939266551c0ec68b437f46"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.4.3:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "Ruby"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.4.3?checksum=55a4cd1dcbe5ca27cf65e89a935a482c2bb2284832939266551c0ec68b437f46&download_url=https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.3.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.3.tar.gz"
    source-checksum = "sha256:55a4cd1dcbe5ca27cf65e89a935a482c2bb2284832939266551c0ec68b437f46"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.4.3_linux_x64_jammy_55a4cd1d.tgz"
    version = "3.4.3"

  [[metadata.dependencies]]
    checksum = "sha256:55a4cd1dcbe5ca27cf65e89a935a482c2bb2284832939266551c0ec68b437f46"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.4.3:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "Ruby"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.4.3?checksum=55a4cd1dcbe5ca27cf65e89a935a482c2bb2284832939266551c0ec68b437f46&download_url=https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.3.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.3.tar.gz"
    source-checksum = "sha256:55a4cd1dcbe5ca27cf65e89a935a482c2bb2284832939266551c0ec68b437f46"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.4.3_linux_x64_bionic_55a4cd1d.tgz"
    version = "3.4.3"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.2.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.3.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.4.*"
    id = "ruby"
    patches = 1

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
