api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate MRI version for an app"
  homepage = "https://github.com/paketo-buildpacks/mri"
  id = "paketo-buildpacks/mri"
  keywords = ["ruby", "mri"]
  name = "Paketo Buildpack for MRI"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/mri/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    ruby = "3.1.*"

  [[metadata.dependencies]]
    checksum = "sha256:f298129921fa8483ba808ac069a2a4b58f49884d043001164a4a3c7ae3acd79a"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.4?checksum=a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz"
    source-checksum = "sha256:a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.4_linux_x64_jammy_f2981299.tgz"
    version = "3.1.4"

  [[metadata.dependencies]]
    checksum = "sha256:f1a3af094c7db9480c4f412e8e7a182ab0dee408cfe3595584ed2f3fcf4607b5"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.4?checksum=a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz"
    source-checksum = "sha256:a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.4_linux_x64_bionic_f1a3af09.tgz"
    version = "3.1.4"

  [[metadata.dependencies]]
    checksum = "sha256:87da799d2a3b203296790035b0b77d5d07f9d4cccb0979e7395663e187c03f5e"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.5:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.5?checksum=3685c51eeee1352c31ea039706d71976f53d00ab6d77312de6aa1abaf5cda2c5&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.5.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.5.tar.gz"
    source-checksum = "sha256:3685c51eeee1352c31ea039706d71976f53d00ab6d77312de6aa1abaf5cda2c5"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.5_linux_x64_jammy_87da799d.tgz"
    version = "3.1.5"

  [[metadata.dependencies]]
    checksum = "sha256:9ed8b96eb4df430bffa807542a4e12f890c5e92fe507d96e194e4e528f97f618"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.5:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.5?checksum=3685c51eeee1352c31ea039706d71976f53d00ab6d77312de6aa1abaf5cda2c5&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.5.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.5.tar.gz"
    source-checksum = "sha256:3685c51eeee1352c31ea039706d71976f53d00ab6d77312de6aa1abaf5cda2c5"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.5_linux_x64_bionic_9ed8b96e.tgz"
    version = "3.1.5"

  [[metadata.dependencies]]
    checksum = "sha256:06d97d48e1e67a09f632c5950546dd120f270e682ad9c2f4a6b7ed8d9397cd34"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.3:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.3?checksum=af7f1757d9ddb630345988139211f1fd570ff5ba830def1cc7c468ae9b65c9ba&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.3.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.3.tar.gz"
    source-checksum = "sha256:af7f1757d9ddb630345988139211f1fd570ff5ba830def1cc7c468ae9b65c9ba"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.3_linux_x64_jammy_06d97d48.tgz"
    version = "3.2.3"

  [[metadata.dependencies]]
    checksum = "sha256:e75372d1242285d9aacf6ed87ed7e9354979c8b0c75a84eab39da90e6943f906"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.3:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.3?checksum=af7f1757d9ddb630345988139211f1fd570ff5ba830def1cc7c468ae9b65c9ba&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.3.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.3.tar.gz"
    source-checksum = "sha256:af7f1757d9ddb630345988139211f1fd570ff5ba830def1cc7c468ae9b65c9ba"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.3_linux_x64_bionic_e75372d1.tgz"
    version = "3.2.3"

  [[metadata.dependencies]]
    checksum = "sha256:7e7ac3e87d9daa8ccafeb2de956ea5f04e19ac014dcfcce0c4e316c5e835f995"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.4?checksum=c72b3c5c30482dca18b0f868c9075f3f47d8168eaf626d4e682ce5b59c858692&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.4.tar.gz"
    source-checksum = "sha256:c72b3c5c30482dca18b0f868c9075f3f47d8168eaf626d4e682ce5b59c858692"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.4_linux_x64_jammy_7e7ac3e8.tgz"
    version = "3.2.4"

  [[metadata.dependencies]]
    checksum = "sha256:89cb55b942d98fe7e216cd45aea409c6e3a3d0d22e0c681258dc41f8fc5d2803"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.4?checksum=c72b3c5c30482dca18b0f868c9075f3f47d8168eaf626d4e682ce5b59c858692&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.4.tar.gz"
    source-checksum = "sha256:c72b3c5c30482dca18b0f868c9075f3f47d8168eaf626d4e682ce5b59c858692"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.4_linux_x64_bionic_89cb55b9.tgz"
    version = "3.2.4"

  [[metadata.dependencies]]
    checksum = "sha256:f347e97131ff1df29bc9997b94d27519ad3df7e4e7385b6a09ca0e3bc6a2b214"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.3.0:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.3.0?checksum=96518814d9832bece92a85415a819d4893b307db5921ae1f0f751a9a89a56b7d&download_url=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz"
    source-checksum = "sha256:96518814d9832bece92a85415a819d4893b307db5921ae1f0f751a9a89a56b7d"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.3.0_linux_x64_jammy_f347e971.tgz"
    version = "3.3.0"

  [[metadata.dependencies]]
    checksum = "sha256:70d46d54717891c71bd916cf60c473d9df5ffa0aa89f6a11a47c988682f76621"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.3.0:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.3.0?checksum=96518814d9832bece92a85415a819d4893b307db5921ae1f0f751a9a89a56b7d&download_url=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz"
    source-checksum = "sha256:96518814d9832bece92a85415a819d4893b307db5921ae1f0f751a9a89a56b7d"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.3.0_linux_x64_bionic_70d46d54.tgz"
    version = "3.3.0"

  [[metadata.dependencies]]
    checksum = "sha256:3e3a526d4246694bb87d6062a44ede33024016ae4de522d90d10dcf20bb411cf"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.3.1:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.3.1?checksum=8dc2af2802cc700cd182d5430726388ccf885b3f0a14fcd6a0f21ff249c9aa99&download_url=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.1.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.1.tar.gz"
    source-checksum = "sha256:8dc2af2802cc700cd182d5430726388ccf885b3f0a14fcd6a0f21ff249c9aa99"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.3.1_linux_x64_jammy_3e3a526d.tgz"
    version = "3.3.1"

  [[metadata.dependencies]]
    checksum = "sha256:31f9e6d0fccb03d747eca7f9173ca7187d375a9e03c01c7232802b6aef1a118f"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.3.1:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["0BSD", "AGPL-1.0-only", "AGPL-1.0-or-later", "BSD-1-Clause", "BSD-2-Clause", "BSD-2-Clause-Views", "BSD-3-Clause", "BSD-3-Clause-Clear", "BSD-3-Clause-No-Military-License", "BSD-3-Clause-No-Nuclear-License-2014", "BSD-4-Clause-UC", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "JSON", "MIT", "MIT-0", "MIT-advertising", "MIT-feh", "Ruby", "X11-distribute-modifications-variant", "Zlib", "deprecated_AGPL-1.0", "deprecated_GPL-2.0", "deprecated_GPL-2.0+", "deprecated_GPL-2.0-with-bison-exception"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.3.1?checksum=8dc2af2802cc700cd182d5430726388ccf885b3f0a14fcd6a0f21ff249c9aa99&download_url=https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.1.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.1.tar.gz"
    source-checksum = "sha256:8dc2af2802cc700cd182d5430726388ccf885b3f0a14fcd6a0f21ff249c9aa99"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.3.1_linux_x64_bionic_31f9e6d0.tgz"
    version = "3.3.1"

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.2.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.3.*"
    id = "ruby"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[targets.distros]]
name = "ubuntu"
version = "18.04"

[[targets.distros]]
name = "ubuntu"
version = "22.04"
