api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate MRI version for an app"
  homepage = "https://github.com/paketo-buildpacks/mri"
  id = "paketo-buildpacks/mri"
  keywords = ["ruby", "mri"]
  name = "Paketo Buildpack for MRI"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/mri/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    ruby = "3.1.*"

  [[metadata.dependencies]]
    checksum = "sha256:1e003b9b9753d81a076a8034bc70efbed6be6c2d25e5c62c9f50bacf5c166f25"
    cpe = "cpe:2.3:a:ruby-lang:ruby:2.7.7:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@2.7.7?checksum=e10127db691d7ff36402cfe88f418c8d025a3f1eea92044b162dd72f0b8c7b90&download_url=https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.7.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.7.tar.gz"
    source-checksum = "sha256:e10127db691d7ff36402cfe88f418c8d025a3f1eea92044b162dd72f0b8c7b90"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_2.7.7_linux_x64_bionic_1e003b9b.tgz"
    version = "2.7.7"

  [[metadata.dependencies]]
    checksum = "sha256:f0757bb4651a1804328b267c26dbe1a2e8ffcf0e1f04e20f7219ea267634d858"
    cpe = "cpe:2.3:a:ruby-lang:ruby:2.7.8:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@2.7.8?checksum=c2dab63cbc8f2a05526108ad419efa63a67ed4074dbbcf9fc2b1ca664cb45ba0&download_url=https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.8.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.8.tar.gz"
    source-checksum = "sha256:c2dab63cbc8f2a05526108ad419efa63a67ed4074dbbcf9fc2b1ca664cb45ba0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_2.7.8_linux_x64_bionic_f0757bb4.tgz"
    version = "2.7.8"

  [[metadata.dependencies]]
    checksum = "sha256:0de6dcaca9e8dd1efdcf07e400eab8a7a8f19b5b5bdf206cd8da16b59f93752c"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.0.5:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.0.5?checksum=9afc6380a027a4fe1ae1a3e2eccb6b497b9c5ac0631c12ca56f9b7beb4848776&download_url=https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.5.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.5.tar.gz"
    source-checksum = "sha256:9afc6380a027a4fe1ae1a3e2eccb6b497b9c5ac0631c12ca56f9b7beb4848776"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.0.5_linux_x64_bionic_0de6dcac.tgz"
    version = "3.0.5"

  [[metadata.dependencies]]
    checksum = "sha256:f2dbef7e3cd197b81de4f1a9493c16a51ab9dc62b1bbbcd52f48ce8b18c996a6"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.0.6:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "FSFUL", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.0.6?checksum=6e6cbd490030d7910c0ff20edefab4294dfcd1046f0f8f47f78b597987ac683e&download_url=https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.6.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.6.tar.gz"
    source-checksum = "sha256:6e6cbd490030d7910c0ff20edefab4294dfcd1046f0f8f47f78b597987ac683e"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.0.6_linux_x64_bionic_f2dbef7e.tgz"
    version = "3.0.6"

  [[metadata.dependencies]]
    checksum = "sha256:a9c084d0785d047f9b2394cccfb16acd326654c74f201abd6d220eef386addca"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.3:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.3?checksum=5ea498a35f4cd15875200a52dde42b6eb179e1264e17d78732c3a57cd1c6ab9e&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.3.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.3.tar.gz"
    source-checksum = "sha256:5ea498a35f4cd15875200a52dde42b6eb179e1264e17d78732c3a57cd1c6ab9e"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.3_linux_x64_jammy_a9c084d0.tgz"
    version = "3.1.3"

  [[metadata.dependencies]]
    checksum = "sha256:04ebd8ebc799ad9cb877fc5ea5deced163b481bb113614cf59ec9a5b602cb055"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.3:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.3?checksum=5ea498a35f4cd15875200a52dde42b6eb179e1264e17d78732c3a57cd1c6ab9e&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.3.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.3.tar.gz"
    source-checksum = "sha256:5ea498a35f4cd15875200a52dde42b6eb179e1264e17d78732c3a57cd1c6ab9e"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.3_linux_x64_bionic_04ebd8eb.tgz"
    version = "3.1.3"

  [[metadata.dependencies]]
    checksum = "sha256:f298129921fa8483ba808ac069a2a4b58f49884d043001164a4a3c7ae3acd79a"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.4?checksum=a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz"
    source-checksum = "sha256:a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.4_linux_x64_jammy_f2981299.tgz"
    version = "3.1.4"

  [[metadata.dependencies]]
    checksum = "sha256:f1a3af094c7db9480c4f412e8e7a182ab0dee408cfe3595584ed2f3fcf4607b5"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.1.4:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.1.4?checksum=a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6&download_url=https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.4.tar.gz"
    source-checksum = "sha256:a3d55879a0dfab1d7141fdf10d22a07dbf8e5cdc4415da1bde06127d5cc3c7b6"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.1.4_linux_x64_bionic_f1a3af09.tgz"
    version = "3.1.4"

  [[metadata.dependencies]]
    checksum = "sha256:6d5f230083742416c4ae9b095621f08568c2bc1e9a1ab04a0e151d5f8405da28"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.1:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.1?checksum=13d67901660ee3217dbd9dd56059346bd4212ce64a69c306ef52df64935f8dbd&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.1.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.1.tar.gz"
    source-checksum = "sha256:13d67901660ee3217dbd9dd56059346bd4212ce64a69c306ef52df64935f8dbd"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.1_linux_x64_jammy_6d5f2300.tgz"
    version = "3.2.1"

  [[metadata.dependencies]]
    checksum = "sha256:7ef264f8c4101cba03c59f5ceee93578008f94b05f925f9526f0784d84edbe51"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.1:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.1?checksum=13d67901660ee3217dbd9dd56059346bd4212ce64a69c306ef52df64935f8dbd&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.1.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.1.tar.gz"
    source-checksum = "sha256:13d67901660ee3217dbd9dd56059346bd4212ce64a69c306ef52df64935f8dbd"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.1_linux_x64_bionic_7ef264f8.tgz"
    version = "3.2.1"

  [[metadata.dependencies]]
    checksum = "sha256:5f9d41d7aea691c00f0dac2ca4ff9a6ac152aff396bd24339bfce0f0fe2473f6"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.2:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.2?checksum=96c57558871a6748de5bc9f274e93f4b5aad06cd8f37befa0e8d94e7b8a423bc&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz"
    source-checksum = "sha256:96c57558871a6748de5bc9f274e93f4b5aad06cd8f37befa0e8d94e7b8a423bc"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.2_linux_x64_jammy_5f9d41d7.tgz"
    version = "3.2.2"

  [[metadata.dependencies]]
    checksum = "sha256:135d83aadce7fda279136fc47cce67992e49844671ad4ad4b355f3a95d8796ee"
    cpe = "cpe:2.3:a:ruby-lang:ruby:3.2.2:*:*:*:*:*:*:*"
    id = "ruby"
    licenses = ["BSD-2-Clause", "BSD-2-Clause-NetBSD", "BSD-3-Clause", "BSD-3-Clause-No-Nuclear-License-2014", "Bison-exception-2.2", "GPL-2.0-only", "GPL-2.0-or-later", "MIT", "MIT-0", "Ruby", "deprecated_GPL-2.0", "deprecated_GPL-2.0+"]
    name = "Ruby"
    purl = "pkg:generic/ruby@3.2.2?checksum=96c57558871a6748de5bc9f274e93f4b5aad06cd8f37befa0e8d94e7b8a423bc&download_url=https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz"
    source = "https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz"
    source-checksum = "sha256:96c57558871a6748de5bc9f274e93f4b5aad06cd8f37befa0e8d94e7b8a423bc"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://artifacts.paketo.io/ruby/ruby_3.2.2_linux_x64_bionic_135d83aa.tgz"
    version = "3.2.2"

  [[metadata.dependency-constraints]]
    constraint = "2.7.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.0.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.1.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.2.*"
    id = "ruby"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
